# Use postgres/example user/password credentials
version: '3.1'

services:
  api:
    container_name: api
    image: spanish-chat:v1.0.0
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env

  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - data:/var/lib/postgresql/data/
  
volumes:
  data: